drupal 9.2.6 -> 9.2.8
(Obtained from : https://www.drupal.org/project/drupal/releases/8.x-9.2.8) 

This is a **patch (bugfix) release of Drupal 9** and is ready for use on production sites. [Learn more about Drupal 9].

Drupal 9.2.x will receive security coverage until June 2022 when Drupal 9.4.0 is released.

If you are upgrading from Drupal 8, read [upgrading a Drupal 8 site to Drupal 9], [9.0.0 release notes], and the [9.2.0 release notes] before upgrading to this release.

Regardless of which version you choose now, features will only be added to Drupal 9 minor releases, so plan to adopt Drupal 9 as soon as possible so that you can easily update to Drupal 9.2 and later.

### Known issues

[Search the issue queue for known issues].

### Changes since 9.2.7

- [Issue #3208849 by yogeshmpawar, cilefen, phenaproxima, mohit_aghera, larowlan, danflanagan8: OEmbedWidget does not display the field's help text, only its own message]
- [Issue #2945033 by longwave, yobottehg, TMWagner, vdsh, jlatorre, catch: HtmlHeadLink processing does not allow for duplicated alternate hreflang links]
- [Issue #2763075 by raman.b, Martijn de Wit, anon, borisson_: Adding new text format gives Uncaught TypeError: f.format_tags.split is not a function]
- [Issue #3203745 by darienmh, Abhijith S, chetanbharambe: Claro theme is incompatible with the Themable Forms module]
- [Issue #3244156 by daffie: Update the Drupal\\KernelTests\\CoretitytityQueryAggregateTest::testAggregation() a little to make it pass for SQL Server]
- [Issue #3083561 by Grimreaper, raman.b, ankithashetty, mglaman, bbrala, Wim Leers, quietone: Add explicit test coverage for JSON:API filtering on a datetime field]
- [Issue #3073294 by Wim Leers, oknate: Remove obsolete @todo for "Undo bug when first inserting media into unfocused CKEditor"]
- [Issue #2957953 by alexpott, sleitner, pobster, Berdir, mohit_aghera, kishor_kolekar, joegraduate, trackleft2, bappa.sarkar, acbramley, ankithashetty, paulocs, batkor, dhirendra.mishra, seanB, priyanka.sahni, Abhijith S, chetanbharambe, vikashsoni, anmolgoyal74, Webbeh, larowlan, hudri, ryan.gibson, amietpatial, ddhuri, capysara, runeasgar, saranya ashokkumar, shimpy, nikitagupta: Editing menus user-experience has regressed]
- [Issue #990218 by Lendude, sun, tim.plunkett, mr.baileys, joachim: Machine name field throws notices if before source field]
- [Issue #3205866 by danflanagan8, phenaproxima: media_requirements() should report missing source fields]
- [Issue #3225227 by Matroskeen, quietone, Kristen Pol: Fix source plugin documentation]
- [Issue #3020876 by alex_optim, sakiland, batkor, pfrenssen, mohit_aghera, i-trokhanenko, drclaw, iamdroid, Grayle, tim.plunkett, gun_dose, acbramley, Chris Burge, Sam152, longwave: Contextual links of reusable content blocks are not displayed when rendering entities built via Layout Builder]
- [Issue #3241318 by alexpott: core/tests/Drupal/Tests/Composer/Plugin/Scaffold/fixtures/scripts/disable-git-bin/git is an odd file and it has the file mode 755]
- [Issue #3116481 by joachim, daffie: Convert EntityViewsDataTest from a unit test to a kernel test]
- [Issue #3203009 by quietone, Gauravmahlawat, joachim, catch: the methods in FieldableEntity should document how they are meant to be used]
- [Issue #3231861 by Lendude, GuyPaddock: PHP errors when overriding the query settings]
- [Issue #2784783 by RytoEX, quietone, jofitz, Charlotte17, Anybody, tomhollevoet, catch, Grevil: Migration of nodes with cck nodereferrer fields fails (SQL error)]
- [Issue #3088917 by quietone, gbirch, marvil07, Wim Leers: Map text_plain field formatter to basic_string for long text fields]
- [Issue #3232681 by Matroskeen, danflanagan8, kpaxman, quietone: FieldLink process plugin treats protocol-relative external URLs as internal ones]
- [Issue #3187616 by quietone, huzooka, Wim Leers, danflanagan8: Fix TermTranslation query and add missing source plugin test]
- [Issue #3199578 by quietone, danflanagan8, huzooka: Fix EntityReferenceTranslationDeriver process pipeline]
- [Issue #3219140 by danflanagan8, huzooka, quietone, Wim Leers: d7_language_content_comment_settings triggers MigrateException if the source bundle is longer than 32 chars: use migration_lookup]
- [Issue #2909805 by googletorp, fgm, dagmar, ankithashetty: LogMessageParser breaks messages containing braces]
- [Issue #3227370 by pfrenssen: Toolbar menu theme override omits the 'menu_name' variable]
- [Issue #2974156 by MegaChriz, k4v, John.nie, jian he, darrenwh, jurgenhaas, daffie, DuneBL, alexpott: TypeError: Argument 1 passed to _editor_get_file_uuids_by_field() must implement interface Drupal\\CoretitytityInterface]
- [Issue #3212670 by Sakthivel M, shashwat-tiwari, kiran.kadam911, Gauravmahlawat, mherchel: Olivero: Z-index issue with the search bar]
- [Issue #3242469 by mherchel, andy-blum, scorbine: Insufficient contrast on Olivero's inactive vertical form labels]
- [Issue #3242456 by mherchel, andy-blum, scorbine: Insufficient contrast on Olivero's fieldset elements]
- [Issue #3223271 by mherchel, bnjmnm, pjudge, lauriii, javi-er, andrewmacpherson: Olivero: Select dropdown icons need more contrast in Windows High Contrast mode]
- [Issue #3223281 by mherchel, andy-blum, andrewmacpherson, mgifford, mikemai2awesome: Olivero: Primary nav search icon invisible in forced-colors mode in MS Edge]
- [Issue #2936067 by pfrenssen, bradjones1, nod_, eiriksm, DuaelFr, Clemens Sahs, AndyF, alexpott, lauriii, idimopoulos: CSS aggregation fails on many variations of @import]
- [Issue #3219340 by lauriii, bnjmnm, mherchel: Vertical tabs with #parents are broken in Claro]
- [Issue #3228000 by bbrala, larowlan, GuyPaddock, Wim Leers, bradjones1, alexpott, catch, e0ipso: Users deleted via JSON:API DELETE don't follow the site-wide cancel_method in the user settings]
- [Issue #3192365 by Symbioquine, tbradbury, mxr576, alexpott, longwave: Race Condition in 'public://simpletest' mkdir Call]